from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True
    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estadio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("api_football_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("nombre", models.CharField(max_length=200)),
                ("ciudad", models.CharField(blank=True, max_length=120)),
                ("pais", models.CharField(blank=True, max_length=100)),
                ("capacidad", models.IntegerField(blank=True, null=True)),
                ("direccion", models.CharField(blank=True, max_length=250)),
                ("superficie", models.CharField(blank=True, max_length=100)),
                ("latitud", models.FloatField(blank=True, null=True)),
                ("longitud", models.FloatField(blank=True, null=True)),
            ],
            options={"verbose_name": "Estadio", "verbose_name_plural": "Estadios", "ordering": ["nombre"]},
        ),
        migrations.CreateModel(
            name="Liga",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("codigo", models.CharField(max_length=10, unique=True)),
                ("nombre", models.CharField(max_length=100)),
                ("pais", models.CharField(blank=True, max_length=100)),
                ("api_football_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("api_football_logo", models.URLField(blank=True)),
            ],
            options={"verbose_name": "Liga", "verbose_name_plural": "Ligas"},
        ),
        migrations.CreateModel(
            name="Equipo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("id_externo", models.IntegerField(blank=True, null=True, unique=True)),
                ("api_football_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("nombre", models.CharField(max_length=150)),
                ("nombre_corto", models.CharField(blank=True, max_length=50)),
                ("escudo_url", models.URLField(blank=True)),
                ("fundado", models.IntegerField(blank=True, null=True)),
                ("estadio", models.CharField(blank=True, max_length=150)),
                ("pais", models.CharField(blank=True, max_length=100)),
                ("liga", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="equipos", to="estadisticas.liga")),
                ("estadio_obj", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="equipos", to="estadisticas.estadio")),
            ],
            options={"verbose_name": "Equipo", "verbose_name_plural": "Equipos", "ordering": ["nombre"]},
        ),
        migrations.CreateModel(
            name="Jugador",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("id_externo", models.IntegerField(blank=True, null=True, unique=True)),
                ("api_football_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("nombre", models.CharField(max_length=150)),
                ("posicion", models.CharField(blank=True, choices=[("POR","Portero"),("DEF","Defensa"),("MED","Mediocampista"),("DEL","Delantero")], max_length=3)),
                ("posicion_detalle", models.CharField(blank=True, max_length=80)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("nacionalidad", models.CharField(blank=True, max_length=100)),
                ("dorsal", models.IntegerField(blank=True, null=True)),
                ("foto_url", models.URLField(blank=True)),
                ("lesionado", models.BooleanField(default=False)),
                ("equipo", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="jugadores", to="estadisticas.equipo")),
            ],
            options={"verbose_name": "Jugador", "verbose_name_plural": "Jugadores", "ordering": ["nombre"]},
        ),
        migrations.CreateModel(
            name="Partido",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("id_externo", models.IntegerField(blank=True, null=True, unique=True)),
                ("api_football_id", models.IntegerField(blank=True, null=True, unique=True)),
                ("fecha", models.DateTimeField()),
                ("estado", models.CharField(choices=[("PROGRAMADO","Programado"),("EN_JUEGO","En juego"),("FINALIZADO","Finalizado"),("APLAZADO","Aplazado"),("CANCELADO","Cancelado")], default="PROGRAMADO", max_length=20)),
                ("estado_api", models.CharField(blank=True, max_length=30)),
                ("goles_local", models.IntegerField(blank=True, null=True)),
                ("goles_visitante", models.IntegerField(blank=True, null=True)),
                ("goles_local_descanso", models.IntegerField(blank=True, null=True)),
                ("goles_visitante_descanso", models.IntegerField(blank=True, null=True)),
                ("jornada", models.IntegerField(blank=True, null=True)),
                ("arbitro", models.CharField(blank=True, max_length=150)),
                ("ronda", models.CharField(blank=True, max_length=150)),
                ("equipo_local", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="partidos_local", to="estadisticas.equipo")),
                ("equipo_visitante", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="partidos_visitante", to="estadisticas.equipo")),
                ("estadio", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="partidos", to="estadisticas.estadio")),
                ("liga", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="partidos", to="estadisticas.liga")),
            ],
            options={"verbose_name": "Partido", "verbose_name_plural": "Partidos", "ordering": ["-fecha"]},
        ),
        migrations.CreateModel(
            name="EstadisticaPartido",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("posesion_local", models.FloatField(blank=True, null=True)), ("posesion_visitante", models.FloatField(blank=True, null=True)),
                ("tiros_local", models.IntegerField(blank=True, null=True)), ("tiros_visitante", models.IntegerField(blank=True, null=True)),
                ("tiros_puerta_local", models.IntegerField(blank=True, null=True)), ("tiros_puerta_visitante", models.IntegerField(blank=True, null=True)),
                ("tiros_fuera_local", models.IntegerField(blank=True, null=True)), ("tiros_fuera_visitante", models.IntegerField(blank=True, null=True)),
                ("corners_local", models.IntegerField(blank=True, null=True)), ("corners_visitante", models.IntegerField(blank=True, null=True)),
                ("faltas_local", models.IntegerField(blank=True, null=True)), ("faltas_visitante", models.IntegerField(blank=True, null=True)),
                ("tarjetas_amarillas_local", models.IntegerField(blank=True, null=True)), ("tarjetas_amarillas_visitante", models.IntegerField(blank=True, null=True)),
                ("tarjetas_rojas_local", models.IntegerField(blank=True, null=True)), ("tarjetas_rojas_visitante", models.IntegerField(blank=True, null=True)),
                ("pases_local", models.IntegerField(blank=True, null=True)), ("pases_visitante", models.IntegerField(blank=True, null=True)),
                ("precision_pases_local", models.FloatField(blank=True, null=True)), ("precision_pases_visitante", models.FloatField(blank=True, null=True)),
                ("ataques_local", models.IntegerField(blank=True, null=True)), ("ataques_visitante", models.IntegerField(blank=True, null=True)),
                ("ataques_peligrosos_local", models.IntegerField(blank=True, null=True)), ("ataques_peligrosos_visitante", models.IntegerField(blank=True, null=True)),
                ("fuera_de_juego_local", models.IntegerField(blank=True, null=True)), ("fuera_de_juego_visitante", models.IntegerField(blank=True, null=True)),
                ("datos_raw", models.JSONField(blank=True, default=dict)),
                ("partido", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="estadisticas", to="estadisticas.partido")),
            ],
            options={"verbose_name":"Estadística de partido","verbose_name_plural":"Estadísticas de partidos"},
        ),
        migrations.CreateModel(
            name="ClimaPartido",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("temperatura", models.FloatField(blank=True, null=True)), ("sensacion_termica", models.FloatField(blank=True, null=True)),
                ("humedad", models.FloatField(blank=True, null=True)), ("precipitacion", models.FloatField(blank=True, null=True)),
                ("probabilidad_precipitacion", models.FloatField(blank=True, null=True)), ("viento_kmh", models.FloatField(blank=True, null=True)),
                ("codigo_clima", models.IntegerField(blank=True, null=True)), ("descripcion", models.CharField(blank=True, max_length=120)),
                ("fuente", models.CharField(default="open-meteo", max_length=50)), ("datos_raw", models.JSONField(blank=True, default=dict)),
                ("partido", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="clima", to="estadisticas.partido")),
            ],
            options={"verbose_name":"Clima del partido","verbose_name_plural":"Clima de partidos"},
        ),
    ]
